### ISSUE TITLE
transfer the firebase configuration to env file 

### ISSUE THREAD

**Issue by dipandhali2021** [dipandhali2021/CineMagic#12]
There should be no configuration for Firebase (`src\components\Firebase\firebase.js`) in the project code, and the Firebase configuration should be transferred to the env file. The config file can be used from the root directory of the repository.

**Comment by Kriishna1** [comment]
please assign to me

**Comment by Musaveershaik** [comment]
Kindly assign me this task under Hacktoberfest2024, Thanku.
