### ISSUE TITLE
Change margin top to prevent overlapping

### ISSUE THREAD

**Issue by dipandhali2021** [dipandhali2021/CineMagic#13]
Issue: 
- In some movie pages image poster div is overlapping with navbar
Implemention: 
- navigate to `src\components\Movie_basic_details\style.scss`
- In poster-block div scss change the margin top in percentage form something like `margin-top: 40%;`

**Comment by stg2209** [comment]
Could i be assigned this issue please ?

**Comment by stg2209** [comment]
I have opened a pr (#19 ) regarding it.
